android_library(
  name = "jenkins-common",
  custom_package = "com.app.jenkins_common",
  manifest = "src/main/AndroidManifest.xml",
  resource_files = glob(["src/main/res/**"]),
  srcs = glob(["Src/main/java/**"]),
  visibility = ["//visibility:public"],
  deps = [
    "@androidsdk//com.android.support:appcompat-v7-25.0.0",
    "@androidsdk//com.android.support:design-25.0.0",
    "@androidsdk//com.android.support:recyclerview-v7-25.0.0",
    "@androidsdk//com.android.support:support-annotations-25.0.0",
  ]
)

